on:
  workflow_dispatch:
  push:

env:
  TF_INPUT: false
  TF_IN_AUTOMATION: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init
        run: terraform init
      - name: init
        run: terraform apply -auto-approve
